--- 
title: "20230719_test"
author: "Shilin Zhao<br><small>Department of Biostatistics<br>Vanderbilt University School of Medicine</small>"
date: "<small>`r Sys.Date()`</small>"
output:
  rmdformats::robobook:
    highlight: kate
    number_sections: no
    code_folding: hide
    toc_depth: 3
    toc_float:
      collapsed: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
editor_options:
  markdown:
    wrap: 72
# output:
#   html_document:
#     toc: yes
#     toc_depth: 2
#     number_sections: true
#     # toc_float: 
#     #   collapsed: true
#     # code_folding: hide
#     # theme: cerulean
#     # keep_md: true
description: "some description ..."
---

```{css,echo = FALSE}
.book .book-body .page-inner {
    max-width: 1200px;
}
``` 

```{r setup,echo=FALSE}
#require(Hmisc)    # provides knitrSet and other functions
#knitrSet(lang='markdown', fig.path='png/', fig.align='left', w=6.5, h=4.5, cache=TRUE)
# If using blogdown: knitrSet(lang='blogdown')


knitr::opts_chunk$set(echo = FALSE)
options(width = 3000)

#Hmisc package html Special characters issue
options(htmlSpecialType='&')
```


<!-- # Functions and packages -->

https://www.danieldsjoberg.com/gtsummary/articles/gallery.html

```{r,message=FALSE,warning=FALSE}
library(knitr)
library(ggplot2)
library(RColorBrewer)
library(reshape2)
library(formattable)
library(rms)
library(htmlTable)
library(gtsummary)

source("D:\\source\\r_cqs\\myPkg\\R\\summaryTableHtml.R")
source("D:\\source\\r_cqs\\myPkg\\R\\HmiscHtmlTableTtestFunction.R")

##PreDefinedForChangingWorkingFolder##
workDir=Sys.getenv("WORKDIR",unset="D:/workSync/")
#workDir=file.path(Sys.getenv("OneDriveCommercial",unset="D:\\OneDrive - VUMC"),"work")

```


## Make/Load Data
```{r}
rawData<-matrix(nrow=200,ncol=10,rnorm(200*10))
row.names(rawData)<-paste0("Sample",1:200)
colnames(rawData)<-paste0("Feature",1:10)
rawData<-data.frame(rawData,FeatureYN1=sample(c(0,1),200,replace = TRUE),FeatureCategory1=sample(c("F","E"),200,replace = TRUE),FeatureCategory2=sample(c("A","B","C","D"),200,replace = TRUE),stringsAsFactors = TRUE)

```

## Add CI to table
```{r}
rawData %>%
  select(varForTable1,outVar) %>%
  tbl_summary(
    by = outVar,
    type = all_dichotomous() ~ "categorical"
    ) %>%
  add_ci()
```

