--- 
title: "Report Example"
author: "Shilin Zhao<br><small>Department of Biostatistics<br>Vanderbilt University School of Medicine</small>"
date: "<small>`r Sys.Date()`</small>"
output:
  html_document:
    toc: yes
    toc_depth: 2
    number_sections: true
    # toc_float: 
    #   collapsed: true
    code_folding: hide
    # theme: cerulean
    # keep_md: true
description: "some description ..."
---
```{r setup,echo=FALSE}
#require(Hmisc)    # provides knitrSet and other functions
#knitrSet(lang='markdown', fig.path='png/', fig.align='left', w=6.5, h=4.5, cache=TRUE)
# If using blogdown: knitrSet(lang='blogdown')


knitr::opts_chunk$set(echo = TRUE)
options(width = 3000)

#Hmisc package html Special characters issue
options(htmlSpecialType='&')
```


<!-- # Notes -->
<!-- ## Hiding/Moving TOC: -->
<!-- http://biostat.mc.vanderbilt.edu/wiki/Main/KnitrHtmlTemplate -->

<!-- `r source("https://raw.githubusercontent.com/harrelfe/Hmisc/master/R/hidingTOC.r")` -->
<!-- `r hidingTOC(buttonLabel="Outline")` -->

<!-- ## More themes: -->
<!-- http://www.datadreaming.org/post/r-markdown-theme-gallery/ -->


<!-- # Functions and packages -->

```{r,message=FALSE,warning=FALSE}
library(knitr)
library(ggplot2)
library(RColorBrewer)
library(reshape2)
library(formattable)
library(rms)
library(htmlTable)


#source('D:/source/cqsR/R/summaryTableFunctions.R')
devtools::source_url("https://raw.github.com/slzhao/cqsR/master/R/summaryTableFunctions.R")


```


# Make/Load Data

```{r}
rawData<-matrix(nrow=200,ncol=10,rnorm(200*10))
row.names(rawData)<-paste0("Sample",1:200)
colnames(rawData)<-paste0("Feature",1:10)
rawData<-data.frame(rawData,FeatureYN1=sample(c(rep(0,100),rep(1,100)),200),FeatureYN2=as.character(sample(c(rep(0,100),rep(1,100)),200)),FeatureCategory1=sample(c("F","E"),200,replace = TRUE),FeatureCategory2=sample(c("A","B","C","D"),200,replace = TRUE),stringsAsFactors = TRUE)

```

# Table 1: Paired Test

```{r,results='asis'}


tableOut=summaryPairedTable(rawData,groupCol="FeatureYN1",varCols=c("FeatureYN2","Feature6"))
printSummaryPairedTable(tableOut)

tableOut=summaryPairedTable(rawData,varCols=c("FeatureYN2","Feature6"),varColsPaired=c("FeatureYN1","Feature7"),nonPairedTest = TRUE)
printSummaryPairedTable(tableOut)


```


# Table 1: Continuous Group Variable

```{r,results='asis'}
temp<-summaryTable(rawData,variables=c("Feature1","Feature2","FeatureYN1","FeatureCategory2"),groupVariable="Feature3")
printSummaryTable(temp)
```


# Table Example: Showing data.frame in a html table
```{r,results='asis'}
library(htmlTable)
htmlTable(iris[1:3,1:3])


kable(iris[1:3,1:3], 
      caption="A test table")
```


